import React from "react";
import Head from "next/head";
import { Layout, Menu } from "antd";
import Sidebar from "./sidebar";

export default function LayoutWrapper({ children }) {
  return (
    <div>
      <Head>
        <title>SIWA - Sistem Informasi Warung</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <Sidebar />
        <Layout>
          <Layout.Header
            className="site-layout-sub-header-background"
            style={{ padding: 0 }}
          >
            <Menu theme="dark" mode="horizontal" style={{ float: "right" }}>
              <Menu.Item key="1">Logout</Menu.Item>
            </Menu>
          </Layout.Header>
          <Layout.Content>
            <div className="site-layout-background" style={{ minHeight: "100vh", padding: 24 }}>{children}</div>
          </Layout.Content>
        </Layout>
      </Layout>
    </div>
  );
}
