import React, { useEffect } from "react";
import Head from "next/head";
import { Layout, Menu } from "antd";
import Sidebar from "./sidebar";
import { useSelector } from "react-redux";

export const LayoutWrapper = ({ children }) => {

  const user = useSelector(state => state.auth.user)

  return (
    <>
      <Head>
        <title>SIWA - Sistem Informasi Warung</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <Sidebar />
        <Layout>
          <Layout.Header
            style={{ padding: 0 }}
          >
            <Menu theme="dark" mode="horizontal" style={{ float: "right" }}>
              <Menu.Item key="1" >Logout</Menu.Item>
            </Menu>
          </Layout.Header>
          <Layout.Content>
            <div className="site-layout-background" style={{ minHeight: "100vh", padding: 24 }}>{children}</div>
          </Layout.Content>
        </Layout>
      </Layout>
    </>
  );
}

// LayoutWrapper = wrapper.withRedux(initStore, (state) => ({ user: state.auth.user }))(LayoutWrapper)

export default LayoutWrapper